'use client'
import { useEffect, createContext } from 'react'
import { subscribe } from '../lib/socket.js'
import { useToast } from './Toast.js'

const RealtimeContext = createContext(null)

export function RealtimeProvider({ children }) {
  const toast = useToast()

  useEffect(() => {
    // All events arrive on the single 'events' channel (relayed from EVENTS_CHANNEL Redis key)
    const unsub = subscribe('events', (data) => {
      const event = data?.event || data

      switch (event) {
        // Social posts
        case 'post.published':
          toast.success('Post published successfully')
          break
        case 'post.failed':
          toast.error(`Post failed to publish${data.error ? `: ${data.error}` : ''}`)
          break
        case 'post.scheduled':
          toast.info('Post scheduled')
          break
        case 'post.drafted':
          toast.info('Draft saved')
          break
        case 'post.publish_requested':
          toast.info('Publishing post…')
          break

        // Campaigns
        case 'campaign.assets_generated':
          toast.success('Campaign assets generated by AI')
          break
        case 'campaign.optimized':
          toast.success('Campaign optimization complete')
          break
        case 'campaign.optimize_requested':
          toast.info('Campaign optimization queued…')
          break

        // Landing pages
        case 'landing_page.content_generated':
          toast.success('Landing page content generated')
          break

        // Integrations
        case 'integration.connected':
          toast.success(`${data.provider || 'Provider'} connected successfully`)
          break

        // Budget alerts
        case 'budget_alert':
          toast.error(`Budget alert: campaign "${data.campaign_name}" has reached ${data.percent}% of budget`)
          break

        // Account events (legacy compatibility)
        case 'account_added':
        case 'agentmarket:account_added':
          toast.success('Account connected')
          break
        case 'account_unauthorized':
        case 'agentmarket:account_unauthorized':
          toast.error('Account disconnected — please reconnect it in Accounts settings.')
          break

        default:
          break
      }
    })

    return () => typeof unsub === 'function' && unsub()
  }, [])

  return <RealtimeContext.Provider value={{}}>{children}</RealtimeContext.Provider>
}
