'use client'
import { useEffect, createContext } from 'react'
import { subscribe } from '../lib/socket.js'
import { useToast } from './Toast.js'

const RealtimeContext = createContext(null)

export function RealtimeProvider({ children }) {
  const toast = useToast()

  useEffect(() => {
    // All events arrive on the single 'events' channel (relayed from EVENTS_CHANNEL Redis key)
    let unsub = () => {}
    try {
      unsub = subscribe('events', (data) => {
      const event = data?.event || data

      switch (event) {
        // Social posts
        case 'post.published':
          toast.success('Post published successfully')
          break
        case 'post.failed':
          toast.error(`Post failed to publish${data.error ? `: ${data.error}` : ''}`)
          break
        case 'post.scheduled':
          toast.info('Post scheduled')
          break
        case 'post.drafted':
        case 'post.publish_requested':
          // Agent timeline already shows draft/publish progress — avoid mid-run toast spam.
          break
        case 'comment.analyzed':
          toast.info('Comment analyzed')
          window.dispatchEvent(new CustomEvent('inbox:refresh'))
          break
        case 'comment.synced':
          window.dispatchEvent(new CustomEvent('inbox:refresh'))
          break

        // Campaigns
        case 'campaign.assets_generated':
          toast.success('Campaign assets generated by AI')
          break
        case 'campaign.optimized':
          toast.success('Campaign optimization complete')
          break
        case 'campaign.optimize_requested':
          toast.info('Campaign optimization queued…')
          break

        // Landing pages
        case 'landing_page.content_generated':
          toast.success('Landing page content generated')
          break
        case 'landing_page.published':
          toast.success('Landing page published')
          break
        case 'budget.pacing_analyzed':
          toast.info('Budget pacing snapshot saved')
          break
        case 'budget.reallocation_applied':
          toast.info('Budget reallocation applied')
          break
        case 'ads.bid_optimization_applied':
          toast.info('Bid optimizations applied')
          break
        case 'ads.asset_ab_applied':
          toast.info('A/B test: underperforming ads paused')
          break
        case 'ads.competitive_analysis_complete':
          toast.success('Competitive analysis ready')
          break
        case 'ads.negative_keywords_suggested':
          toast.success(`Negative keyword suggestions ready (${data.count ?? 0})`)
          break

        // Integrations
        case 'integration.connected':
          toast.success(`${data.provider || 'Provider'} connected successfully`)
          break

        // Budget alerts
        case 'budget_alert':
          toast.error(`Budget alert: campaign "${data.campaign_name}" has reached ${data.percent}% of budget`)
          break

        case 'workflow.planned':
        case 'workflow.running':
        case 'workflow.completed':
        case 'approval.required':
        case 'approval.granted':
        case 'step.running':
        case 'step.completed':
          // AI Agent card is the source of truth for workflow progress.
          break
        case 'workflow.failed':
          toast.error(`Workflow failed${data.error ? `: ${data.error}` : ''}`)
          break
        case 'step.failed':
          toast.error(`Workflow step failed${data.error ? `: ${data.error}` : ''}`)
          break

        // Account events (legacy compatibility)
        case 'account_added':
        case 'agentmarket:account_added':
          toast.success('Account connected')
          break
        case 'account_unauthorized':
        case 'agentmarket:account_unauthorized':
          toast.error('Account disconnected — please reconnect it in Accounts settings.')
          break

        default:
          break
      }
      })
    } catch (err) {
      console.warn('[realtime] socket subscribe failed', err)
    }

    return () => typeof unsub === 'function' && unsub()
  }, [])

  return <RealtimeContext.Provider value={{}}>{children}</RealtimeContext.Provider>
}
